import = ["~/.config/alacritty/themes/themes/moonfly.toml"]

[env]
TERM = "xterm-256color"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window]
decorations = "None"
dimensions = { columns = 100, lines = 50 }
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 0.75

[font]
size = 13.0
offset = { x = 0, y = 1 }

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

